version: '3'
services:
  
  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    env_file:
      - ./products/.env
    volumes:
      - .:/app
      - /app/products/node_modules

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
   
    env_file:
      - ./shopping/.env
    volumes:
      - .:/app
      - /app/shopping/node_modules

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - ./customer/.env
    volumes:
      - .:/app
      - /app/customer/node_modules
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - "80:80"
 